Apoteka/Pages/DodajApoteku.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Neo4j.AspNetCore.Identity;
using Apoteka.Models;
using Microsoft.AspNetCore.Identity;
using Neo4jClient.DataAnnotations;
using Neo4jClient;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using System.IO;

namespace Apoteka.Pages
{
    public class DodajApotekuModel : PageModel
    {
        [BindProperty]
        public ApotekaModel Apoteka { get; set; }
        [BindProperty]
        public IList<Lokacija> Lokacije { get; set; }
        [BindProperty]
        public IFormFile Photo { get; set; }

        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<Korisnik> _userManager;
        private readonly AnnotationsContext _context;

        public DodajApotekuModel(UserManager<Korisnik> userManager, AnnotationsContext context, IWebHostEnvironment webHostEnvironment)
        {
            _userManager = userManager;
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            Lokacije = new List<Lokacija>();
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostDodajAsync()
        {

            var korisnik = await _userManager.GetUserAsync(User);

            if (Photo != null)
            {
                if (Apoteka.Slika != null)
                {
                    string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "imagesApoteke", Apoteka.Slika);
                    System.IO.File.Delete(filePath);
                }
                Apoteka.Slika = ProcessUploadedFile();
            }

            await _context.GraphClient.Cypher.Create("(n:Apoteka { ApotekaID:'" + Apoteka.ApotekaID + "', Naziv:'" + Apoteka.Naziv +
               "', Email:'" + Apoteka.Email + "', Direktor:'" + Apoteka.Direktor + "', BrojTelefona:'" + Apoteka.BrojTelefona + "', Slika:'"+Apoteka.Slika+"'})").ExecuteWithoutResultsAsync();

            var apoteka = _context.GraphClient.Cypher.Match("(n:Apoteka)").Where("n.Naziv = '" + Apoteka.Naziv + "' AND n.Direktor= '" + Apoteka.Direktor + "'").Return(n => n.As<Node<string>>());
            var rez = apoteka.Results.Single();
            string id = rez.Reference.Id.ToString();
            Apoteka.ApotekaID = id;
            await _context.GraphClient.Cypher.Match("(n:Apoteka { Naziv:'" + Apoteka.Naziv + "', Direktor:'" + Apoteka.Direktor + "'})").Set("n.ApotekaID = " + id).ExecuteWithoutResultsAsync();

            foreach (Lokacija lok in Lokacije)
            {
                if (lok != null)
                {
                    await _context.GraphClient.Cypher.Create("(n:Lokacija { ID:'" + lok.ID + "', Grad:'" + lok.Grad + "', UlicaBr:'" + lok.UlicaBr +
                   "', BrojTelefona:'" + lok.BrojTelefona + "'}) return n").ExecuteWithoutResultsAsync();

                    var lokacija = _context.GraphClient.Cypher.Match("(n:Lokacija)").Where("n.Grad = '" + lok.Grad + "' AND n.UlicaBr= '" + lok.UlicaBr + "'").Return(n => n.As<Node<string>>());
                    var r = lokacija.Results.Single();
                    string idl = r.Reference.Id.ToString();

                    await _context.GraphClient.Cypher.Match("(n:Lokacija)").Where("n.Grad = '" + lok.Grad + "' AND n.UlicaBr= '" + lok.UlicaBr + "'").Set("n.ID = " + idl).ExecuteWithoutResultsAsync();

                    await _context.GraphClient.Cypher.Match("(a:Apoteka),(b:Lokacija)").Where("a.ApotekaID =" + id + " AND b.ID= " + idl)
                        .Create("(a)-[r:SE_NALAZI_U]->(b) return type(r)").ExecuteWithoutResultsAsync();
                }
            }

            await _context.GraphClient.Cypher.Match("(a:Apoteka),(b:IdentityUser)").Where("a.ApotekaID =" + id + " AND b.UserName= '" + korisnik.UserName + "'")
                                             .Create("(b)-[r:POSEDUJE]->(a) return type(r)").ExecuteWithoutResultsAsync();

            return RedirectToPage("ProfilApoteke",new {id=Apoteka.ApotekaID});
        }
        public string ProcessUploadedFile()
        {
            string uniqueFileName = null;
            if (Photo != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    Photo.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
    }
}

Apoteka/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Apoteka.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Apoteka/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Apoteka.Models;
using Neo4jClient;
using Neo4jClient.Cypher;
using Neo4j.Driver;
using Neo4j.AspNetCore.Identity;
using Neo4jClient.DataAnnotations;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Apoteka.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly AnnotationsContext _context;
        private IList<Proizvod> Proizvodi { get; set; }
        private IList<string> Ids { get; set; }
        [BindProperty]
        public IList<Proizvod> ProizvodiPretraga { get; set; }
        [BindProperty]
        public IList<Ima> Ima { get; set; }
        [BindProperty]
        public IList<Ima> PretragaIma { get; set; }
        [BindProperty]
        public List<SelectListItem> GradoviFilter { get; set; }
        [BindProperty]
        public List<SelectListItem> SortirajPo { get; set; }
        IEnumerable<Ima> query;

        [BindProperty(SupportsGet = true)]
        public string FilterNaziv { get; set; }
        [BindProperty(SupportsGet = true)]
        public string GradFilter { get; set; }
        [BindProperty(SupportsGet = true)]
        public string SortirajPoFilter { get; set; }
        public IndexModel(ILogger<IndexModel> logger, AnnotationsContext context)
        {
            _context = context;
            _logger = logger;
            Proizvodi = new List<Proizvod>();
            Ids = new List<string>();
            ProizvodiPretraga = new List<Proizvod>();
            GradoviFilter = new List<SelectListItem>();
            Ima = new List<Ima>();
            PretragaIma = new List<Ima>();

            List<string> SviGradovi = new List<string>();
            var svigradovi = _context.GraphClient.Cypher.Match("(p:Lokacija)").Return(p => p.As<Node<string>>());
            var rezul = svigradovi.Results;
            SviGradovi = rezul.Select(node => JsonConvert.DeserializeObject<Lokacija>(node.Data)).Select(grad => grad.Grad).Distinct().ToList();

            foreach(var grad in SviGradovi)
            {
                SelectListItem item = new SelectListItem { Text = grad, Value = grad };
                GradoviFilter.Add(item);
            }

            SortirajPo = new List<SelectListItem>
            {
                new SelectListItem { Text="Prvo najjeftinije", Value = "Najjeftinije"},
                new SelectListItem { Text="Prvo najskuplje", Value = "Najskuplje"}
            };
        }

        public async Task OnGetAsync()
        {
            var proizvod = _context.GraphClient.Cypher.Match("(p:Proizvod)").Return(p => p.As<Node<string>>());
            var rezul = proizvod.Results;
            Proizvodi = rezul.Select(node => JsonConvert.DeserializeObject<Proizvod>(node.Data)).ToList();

            if (Proizvodi.Count==0)
            {
                _context.GraphClient.Cypher.Create("(n:Proizvod {ID:'' ,Naziv:'IBUPROFEN',Kategorija:'IBUPROFEN', Opis:'film tabl. 30x600mg',Proizvodjac:'Hemofarm',Slika:'ibuprofen-400-mg-67.png'})").ExecuteWithoutResults();
                _context.GraphClient.Cypher.Create("(n:Proizvod {ID:'' ,Naziv:'BRUFEN',Kategorija:'IBUPROFEN', Opis:'film tabl. 30x400mg',Proizvodjac:'Hemofarm',Slika:'brufen1.jpg'})").ExecuteWithoutResults();
                _context.GraphClient.Cypher.Create("(n:Proizvod {ID:'' ,Naziv:'IBUPROFEN',Kategorija:'IBUPROFEN', Opis:'film tabl. 30x200mg',Proizvodjac:'Hemofarm',Slika:'ibuprofen-400-mg-67.png'})").ExecuteWithoutResults();
                _context.GraphClient.Cypher.Create("(n:Proizvod {ID:'' ,Naziv:'DEFRINOL FORTE',Kategorija:'PSEUDOFEDRIN', Opis:'film tabl. 20x(200mg+30mg)',Proizvodjac:'Galenika',Slika:'defrinol-forte.jpg'})").ExecuteWithoutResults();
                _context.GraphClient.Cypher.Create("(n:Proizvod {ID:'' ,Naziv:'RINASEK',Kategorija:'PSEUDOFEDRIN', Opis:'sirup 100ml (100mg+30mg)/5ml',Proizvodjac:'Hemofarm',Slika:'unnamed.jpg'})").ExecuteWithoutResults();
                _context.GraphClient.Cypher.Create("(n:Proizvod {ID:'' ,Naziv:'OPERIL',Kategorija:'KAPI ZA NOS', Opis:'kapi 0.05% 10ml',Proizvodjac:'Lek',Slika:'operil-kapi-za-nos-za-odrasle-10ml-640x640.jpg'})").ExecuteWithoutResults();
                _context.GraphClient.Cypher.Create("(n:Proizvod {ID:'' ,Naziv:'MARISOL',Kategorija:'KAPI ZA NOS', Opis:'kapi 2.2% 50ml',Proizvodjac:'Esensa',Slika:'marisol-imuno-600x600.jpg'})").ExecuteWithoutResults();
                _context.GraphClient.Cypher.Create("(n:Proizvod {ID:'' ,Naziv:'JSP FFP2 325 TYPHOON ',Kategorija:'ZASTITNE MASKE', Opis:'FFP2 325 TYPHOON ',Proizvodjac:'JSP',Slika:'maska-disajni-organi-zastita-disanje-jsp-typhoon-zdj-325.jpg'})").ExecuteWithoutResults();
                proizvod = _context.GraphClient.Cypher.Match("(p:Proizvod)").Return(p => p.As<Node<string>>());
                rezul = proizvod.Results;
                Proizvodi = rezul.Select(node => JsonConvert.DeserializeObject<Proizvod>(node.Data)).ToList();
            }

            Ids = rezul.Select(node => JsonConvert.DeserializeObject<string>(node.Reference.Id.ToString())).ToList();
            for (int i=0;i<Proizvodi.Count;i++)
            {
                Proizvodi[i].ID = Ids[i];
                await _context.GraphClient.Cypher.Match("(n:Proizvod { Naziv:'" + Proizvodi[i].Naziv + "', Proizvodjac:'" + Proizvodi[i].Proizvodjac + "',Opis:'"+Proizvodi[i].Opis+"' })").Set("n.ID = " + Ids[i]).ExecuteWithoutResultsAsync();

            }


            List<Lokacija> SveLokacije = new List<Lokacija>();
            var lokacija = _context.GraphClient.Cypher.Match("(l:Lokacija)-[:IMA]->(p:Proizvod)").Return(l => l.As<Node<string>>());
            var rezultat = lokacija.Results.Distinct();
            SveLokacije = rezultat.Select(node => JsonConvert.DeserializeObject<Lokacija>(node.Data)).ToList();


            //PRETRAGA

            int brojac = 0;
            foreach (Lokacija lok in SveLokacije)
            {
                List<Proizvod> pomProizvod = new List<Proizvod>();
                var imaProizvode = _context.GraphClient.Cypher.Match("(l:Lokacija { ID: "+lok.ID+"})-[:IMA]->(p:Proizvod)").Return(p => p.As<Node<string>>());
                var provera = imaProizvode.Results;
                pomProizvod = provera.Select(node => JsonConvert.DeserializeObject<Proizvod>(node.Data)).ToList();

                var qapoteka = _context.GraphClient.Cypher.Match("(l:Lokacija { ID: " + lok.ID + "})<-[:SE_NALAZI_U]-(a:Apoteka)").Return(a => a.As<Node<string>>());
                var rez = qapoteka.Results.Single();
                var apoteka = JsonConvert.DeserializeObject<ApotekaModel>(rez.Data);

                foreach (Proizvod p in pomProizvod)
                {
                    Ima i = new Ima();
                    i.LokacijaVeza = lok;
                    i.ApootekaVeza = apoteka;
                    var cenequery = _context.GraphClient.Cypher.Match("(p:Proizvod { ID:" + p.ID + "})<-[r:IMA]-(l:Lokacija {ID :" + lok.ID + "})").Return(r => r.As<Node<string>>());
                    var c = cenequery.Results.Single();
                    string idv = c.Reference.Id.ToString();
                    string cena = JObject.Parse(c.Data)["Cena"].ToString();
                    i.ProizvodVeza = p;
                    i.Cena = cena;
                    i.VezaID = idv;
                    Ima.Add(i);
                    brojac++;
                }
            }

        if (Ima.Count > 0){
                query = Ima.Select(x => x).OrderBy(x => Int32.Parse(x.Cena));

                if (!string.IsNullOrEmpty(SortirajPoFilter))
                {
                    if (SortirajPoFilter == "Najjeftinije")
                    {
                        query = Ima.Select(x => x).OrderBy(x => Int32.Parse(x.Cena));
                    }
                    if (SortirajPoFilter == "Najskuplje")
                    {
                        query = Ima.Select(x => x).OrderByDescending(x => Int32.Parse(x.Cena));
                    }
                }

                if (!string.IsNullOrEmpty(GradFilter))
                {
                    query = Ima.Select(x => x).Where(x => x.LokacijaVeza.Grad == GradFilter);
                }

                if (!string.IsNullOrEmpty(FilterNaziv))
                {
                    query = Ima.Select(x => x).Where(x => x.ProizvodVeza.Naziv.StartsWith(FilterNaziv.ToUpper()));
                }

                if (!string.IsNullOrEmpty(FilterNaziv) && !string.IsNullOrEmpty(GradFilter))
                {
                    query = Ima.Select(x => x).Where(x => x.ProizvodVeza.Naziv.StartsWith(FilterNaziv.ToUpper()) && x.LokacijaVeza.Grad == GradFilter);
                }

                if (!string.IsNullOrEmpty(FilterNaziv) && !string.IsNullOrEmpty(SortirajPoFilter))
                {
                    if (SortirajPoFilter == "Najjeftinije")
                    {
                        query = Ima.Select(x => x).Where(x=>x.ProizvodVeza.Naziv.StartsWith(FilterNaziv.ToUpper())).OrderBy(x => Int32.Parse(x.Cena));
                    }
                    if (SortirajPoFilter == "Najskuplje")
                    {
                        query = Ima.Select(x => x).Where(x => x.ProizvodVeza.Naziv.StartsWith(FilterNaziv.ToUpper())).OrderByDescending(x => Int32.Parse(x.Cena));
                    }
                }

                if (!string.IsNullOrEmpty(GradFilter) && !string.IsNullOrEmpty(SortirajPoFilter))
                {
                    if (SortirajPoFilter == "Najjeftinije")
                    {
                        query = Ima.Select(x => x).Where(x => x.LokacijaVeza.Grad == GradFilter).OrderBy(x => Int32.Parse(x.Cena));
                    }
                    if (SortirajPoFilter == "Najskuplje")
                    {

Apoteka/Pages/SveApoteke.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Neo4j.AspNetCore.Identity;
using Neo4jClient;
using Neo4jClient.DataAnnotations;
using Apoteka.Models;
using Newtonsoft.Json;

namespace Apoteka.Pages
{
    public class SveApotekeModel : PageModel
    {
        private readonly AnnotationsContext _context;
        [BindProperty]
        public IList<ApotekaModel> Apoteke { get; set; }

        public SveApotekeModel(AnnotationsContext context)
        {
            _context = context;
            Apoteke = new List<ApotekaModel>();
        }
        public void OnGet()
        {
            var apoteke = _context.GraphClient.Cypher.Match("(a:Apoteka)").Return(a => a.As<Node<string>>());
            var rez = apoteke.Results;
            Apoteke = rez.Select(node => JsonConvert.DeserializeObject<ApotekaModel>(node.Data)).ToList();
        }
    }
}

Apoteka/Pages/DodajApoteku.cshtml
@page
@model Apoteka.Pages.DodajApotekuModel
@{
    ViewData["Title"] = "Dodaj apoteku";
}
@inject SignInManager<Korisnik> SignInManager
@inject UserManager<Korisnik> UserManager

<link rel="stylesheet" href="~/css/DodajApoteku.css">

@if (SignInManager.IsSignedIn(User))
{
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <form method="post" enctype="multipart/form-data">
                <h4>Dodaj Apoteku</h4>
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label hidden asp-for="Apoteka.ApotekaID"></label>
                    <input hidden asp-for="Apoteka.ApotekaID" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Apoteka.Naziv">Naziv: </label>
                    <input asp-for="Apoteka.Naziv" class="form-control" placeholder="Unesite naziv apoteke" autocomplete="off" required />
                </div>
                <div class="form-group">
                    <label asp-for="Apoteka.Email">Email: </label>
                    <input asp-for="Apoteka.Email" class="form-control" placeholder="Unesite email adresu" autocomplete="off" required />
                </div>
                <div class="form-group">
                    <label asp-for="Apoteka.Direktor">Direktor: </label>
                    <input asp-for="Apoteka.Direktor" class="form-control" placeholder="Unesite ime i prezime direktora apoteke" autocomplete="off" required />
                </div>
                <div class="form-group">
                    <label asp-for="Apoteka.BrojTelefona">Broj telefona: </label>
                    <input asp-for="Apoteka.BrojTelefona" class="form-control" placeholder="Unesite broj telefona" autocomplete="off" required />
                </div>

                <div class="form-group">
                    <label>Vas logo: </label>
                    <div class="custom-file" style="text-align:left; white-space:nowrap;">
                        <input asp-for="Photo" class="custom-file-input form-control" />
                        <label class="custom-file-label">Izaberite fotografiju...</label>
                    </div>
                </div>

                <div class="form-group">
                    <label for="exampleFormControlInput1">Broj lokacija:</label>
                    <input type="number" min="1" class="form-control bend" id="brclanova" placeholder="Unesite broj lokacija">
                    <button type="button" class="btn btn-outline-success" value="CREATE" id="btnNoOfRec" style="margin-top: 20px;">Unesi lokacije</button>
                </div>
                <div>
                    <div id="LokacijeDiv">

                    </div>
                    <div class="dodaj">
                        <button type="submit" asp-page-handler="Dodaj" class="btn btn-success">Dodaj</button>
                    </div>
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>
}
else
{
<div class="row logcheck text-muted"> 
    <div class="col-6">
        <h4>Morate biti prijavljeni!</h4>
        <p><a asp-area="Identity" asp-page="/Account/Login">Uloguj se!</a></p>
    </div>
    <div class="col-6">
        <img src="~/images/login.svg" alt="Login">
    </div>
</div>
}
    <script src="~/temp/jquery-3.4.1.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#btnNoOfRec").click(function () {
                $('#LokacijeDiv').empty();
                var NoOfRec = $('#brclanova').val();

                if (NoOfRec > 0) {
                    createControl(NoOfRec);
                }
            });

            function createControl(NoOfRec) {
                var tbl = "";

                tbl = "<table>" + "<tr>" + "<th>Grad</th>" + "<th>Ulica i broj</th>" + "<th>Broj telefona</th>" + "</tr>";
                for (var i = 0; i < NoOfRec; i++) {
                    tbl += "<tr>" + "<td>" + "<input type='text' name='Lokacije[" + i + "].Grad' autocomplete='off' />" + "</td>" + "<td>" + "<input type='text' name='Lokacije[" + i + "].UlicaBr' autocomplete='off' />" + "</td>" + "<td>" + "<input type='text' name='Lokacije[" + i + "].BrojTelefona' autocomplete='off' />" + "</td>" + "</tr>";
                }
                tbl += "</table>";
                $('#LokacijeDiv').append(tbl);
            }
        });
    </script>
    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(fileName);
            });
        });
    </script>

Apoteka/Pages/ProfilProizvoda.cshtml
@page
@model Apoteka.Pages.ProfilProizvodaModel
@{
    var photoPath = "~/images/Logo.png";
    @if (Model.Proizvod.Slika != "")
    {
        photoPath = "~/images/" + Model.Proizvod.Slika;
    }

    ViewData["Title"] = "Profil proizvoda";
}
<link href="~/css/ProfilProizvoda.css" rel="stylesheet" />
<div class="row sadrzaj">
    <div class="col-md-6 proizvod">
        <form method="post">
            <div class="form-group">
                <label hidden asp-for="@Model.Proizvod.ID"></label>
                <input hidden asp-for="@Model.Proizvod.ID" class="form-control" />
            </div>
            <div class="text-center" style="padding-bottom: 45px;">
                <img src="@photoPath" class="avatar img-circle" alt="avatar" asp-append-version="true" style="border-radius: 5%; width: 260px; height:260px; padding-bottom:10px">
            </div>
            <div class="opis-proizvoda">
                <h4>@Model.Proizvod.Naziv</h4>
                <h6>@Model.Proizvod.Kategorija</h6>
                <div class="form-group">
                    <label asp-for="@Model.Proizvod.Opis">Opis: </label>
                    <input type="text" asp-for="@Model.Proizvod.Opis" class="form-control izmena" disabled />
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Proizvod.Proizvodjac">Proizvođač: </label>
                    <input asp-for="@Model.Proizvod.Proizvodjac" class="form-control izmena" disabled />
                </div>

                @for (var i = 0; i < Model.Apoteke.Count; i++)
                {
                    <button type="button" class="accordion">Apoteka @Model.Apoteke[i].Naziv</button>
                    <div class="panel">
                        <table style="margin-bottom: 10px;">
                            <thead style="color: #8c8c8c;">
                            <th>Grad</th>
                            <th>Ulica i broj</th>
                            <th>Broj telefona</th>
                            <th>Cena(din.)</th>
                            </thead>
                            <tbody id="tbody">
                                @for (var j = 0; j < Model.Imas.Count; j++)
                                {
                                    @if (Model.Apoteke[i] == Model.Imas[j].ApootekaVeza)
                                    {
                                        var a = i + 10;
                                        <tr>
                                            <td>
                                                <input type="text" id="a_@a" class="form-control" asp-for="@Model.Imas[j].LokacijaVeza.Grad" disabled>
                                            </td>
                                            <td>
                                                <input type="text" id="b_@a" class="form-control" asp-for="@Model.Imas[j].LokacijaVeza.UlicaBr" disabled>
                                            </td>
                                            <td>
                                                <input type="text" id="c_@a" class="form-control" asp-for="@Model.Imas[j].LokacijaVeza.BrojTelefona" disabled>
                                            </td>
                                            <td>
                                                <input type="text" id="e_@a" class="form-control" asp-for="@Model.Imas[j].Cena" disabled>
                                            </td>
                                            <td>
                                                <input type="text" id="h_@a" class="form-control" asp-for="@Model.Imas[j].VezaID" hidden>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                }
            </div>
        </form>

    </div>
</div>

<script src="~/temp/jquery-3.4.1.min.js"></script>
<script>
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
        acc[i].addEventListener("click", function () {
            this.classList.toggle("active");
            var panel = this.nextElementSibling;
            if (panel.style.display === "block") {
                panel.style.display = "none";
            } else {
                panel.style.display = "block";
            }
        });
    }
</script>

Apoteka/Pages/SveApoteke.cshtml
@page
@model Apoteka.Pages.SveApotekeModel
@{
    ViewData["Title"] = "Sve apoteke";
}
<link href="~/css/SveApoteke.css" rel="stylesheet" />

<form>

    @if (@Model.Apoteke.Count == 0)
    {
        <div class="row bez-apoteka"> 
            <div class="col-6">
                <a class="text-muted" asp-page="./DodajApoteku">
                    <h5 class="obavestenje"> <ion-icon name="add-circle-outline"></ion-icon> Trenutno nema apoteka! Napravite prvi!</h5>
                </a>
            </div>
            <div class="col-6">
                <img src="~/images/add.svg" alt="Apoteka">
            </div>
        </div>
    }
<div class="row sadrzaj">
    @foreach (var apoteka in @Model.Apoteke)
    {
        var photoPath = "~/images/Logo.png";
        @if (apoteka.Slika != "")
        {
            photoPath = "~/images/" + apoteka.Slika;
        }
        <div class="col-lg-4">
            <div class="card">
                <a class="text-dark" style="text-align: center;" asp-route-Id="@apoteka.ApotekaID" asp-page="/ProfilApoteke">
                    <div class="pozadina"></div>
                    <img class="card-img-top" src="@photoPath" alt="Card image cap" asp-append-version="true" />
                    <h5 class="card-header">@apoteka.Naziv</h5>
                </a>
                <div class="card-body">
                    <h5 class="card-title">Direktor: @apoteka.Direktor</h5>
                    <p class="card-text desc"><ion-icon name="call-outline" style="vertical-align: -2px;"></ion-icon>@apoteka.BrojTelefona</p>
                    <p class="card-text"><ion-icon name="mail-outline" style="vertical-align: -2px;"></ion-icon> @apoteka.Email<br></p>
                </div>
            </div>
        </div>
    }
</form>